### ISSUE TITLE
App down on out of memory error 

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun_rework#104]
Here's the error log for crash. 

Further circumstances: 
- This time it happened within 24h after a fresh launch. 
- The container also quits after this error. 

![image](https://user-images.githubusercontent.com/28865986/135873723-4fb4ec9e-55ca-4914-aa79-3de46bda1b0e.png)

FYI @pvj @baxgas @gygabor I didn't know of another issue for this so I created this one.

**Comment by pvj** [comment]
I've added an `--inspect` option too to the `start` script in on our staging env and re-built and re-started the container. This way it's possible to get profiles from the browser dev console. Will try to do that and locate the leak. 

Thanks for the monitoring @gammaw !

**Comment by baxgas** [comment]
@pvj @gammaw 
See this please
![image](https://user-images.githubusercontent.com/36408851/136751490-03715903-0d90-4293-ae20-b7bbf0a10e2a.png)
https://jcutrer.com/javascript/yarn-build-exit-code-137

**Comment by gammaw** [comment]
Our current experiments - highlights:

- Links prefetch disable 
- Webpack watcher ignore 
- max old space increase
- memwatch

**Comment by gammaw** [comment]
@pvj thanks for these tool additions! For memwatch, I was wondering: 

- As far as I understand, we can now visually see the memwatch reports when running `docker-compose up`  (without the `-d` option), which only applies for the user who runs the command, but other team members cannot not have access to the reports. More importantly, we lose the reports if the app shuts down (either because we shut it down or out of mem). Is there an easy way to write these reports on disk (like a file log)?  
- Again, as far as I understand, all `memwatch` options we use are passive "monitors" in nature, except `gcAfterEvery` which changes the default behavior of gc. At this point, we're trying to diagnose what is happening and this setting may affect the native behavior, so wouldn't it be better to disable it?

**Comment by gammaw** [comment]
We discussed today that 1) @baxgas will create a one-night log with memwatch entries together with the proxy traffic (by running `docker-compose up` on test) and 2) @baxgas will try three stripped-down versions (on respective branches) so that there is i) no arcsi connection, ii) no WP connection, iii) no Azuracast connection. At the end of each experiment we should record the mem status too.

**Comment by gammaw** [comment]
For the history books: using the `siege` load tester we could identify this https://github.com/mmmnmnm/lahmacun_rework/commit/5af0c025a30671110c9a42b50d10d614f5ef31ab strong candidate as responsible commit for the mem leak, and see above https://github.com/mmmnmnm/lahmacun_rework/commit/fe714e9b0a8b7a12897d2837b216b41948d13ca4 commit for fix. The clue is to disable SSR (server-side rendering) for periodically checking the stream server's API to be able to display the on air show in the schedule. 

FYI @molnar-a

**Comment by pvj** [comment]
@gammaw Sorry I did not see your questions until now! Even though we are after the fact, I hope it still provides some value to answer these since they are good questions!

>As far as I understand, we can now visually see the memwatch reports when running docker-compose up (without the -d option), which only applies for the user who runs the command, but other team members cannot not have access to the reports. More importantly, we lose the reports if the app shuts down (either because we shut it down or out of mem). Is there an easy way to write these reports on disk (like a file log)?

If you run it as daemon you can still check the container logs that would show the memwatch numbers (that's why `graph` is `false` so the appended lines for each memwatch entry can be read from there. 

>Again, as far as I understand, all memwatch options we use are passive "monitors" in nature, except gcAfterEvery which changes the default behavior of gc. At this point, we're trying to diagnose what is happening and this setting may affect the native behavior, so wouldn't it be better to disable it?

Yeah, I was thinking that perhaps if the issue is with the garbage collection then adding such option might work around our issue for now.

**Comment by gammaw** [comment]
> If you run it as daemon you can still check the container logs that would show the memwatch numbers (that's why graph is false so the appended lines for each memwatch entry can be read from there.

Even after the container stops due to out of mem? Don't logs disappear with the container?

**Comment by gammaw** [comment]
Looks good so far! We're closing it.
