### ISSUE TITLE
Expose episode details on episode page

### ISSUE THREAD

**Issue by pvj** [mmmnmnm/lahmacun_rework#146]
I do like the simplicity of the details pages but I would think we can guide & inform users better when showing more info about the episodes:

 - original air date
 - episode length (currently no value but the field is present)
 - episode category (talkative, musical, hungarian or english etc.)
 - episode number (I know, I know)
 - Parent show breadcrumb (it exists I think)
 - Does it currently air or not?
 - Navigation (prev. && next episode) maybe?
 

Possibly we could query some similar episodes (length? category? else?) in a block too

**Comment by baxgas** [comment]
@pvj 
_episode length (currently no value but the field is present)_
I didn't find this field, but would be nice in some revision of Arcsi item API!

_Does it currently air or not?_
I can think of getting the info it is the latest in the Show Arcsi episodes block, but it is not a proof it is in Azura? But I can't think of better way for now...

_Navigation (prev. && next episode) maybe?_
Do we really need this? There is a breadcrumb for full Show view with all the episodes. Maybe better would be the Show arcsi episodes list with images and titles, as on the show page, just smaller? 
And of course when we have the tags and all, to have the Related Episodes also...

**Comment by pvj** [comment]
@baxgas 

>episode length
>I didn't find this field, but would be nice in some revision of Arcsi item API!
Since we it is currently still `0` for all episodes we don't return this value to json serialisation. But the key is there and we can add it to our schema. 

The key is simply `length` and returns total seconds as an `Int`

>Does it currently air or not?
>I can think of getting the info it is the latest in the Show Arcsi episodes block, but it is not a proof it is in Azura? But I can't think of better way for now...

There is the key `airing` which indicates whether the episode is currently in our rotation or not. If you use that key we can display on the episode page that this is the one airing at {{ show.day }} - {{ show.start }} There is a known bug currently plaguing this key but from my end I'm glad if there's some pressure to prioritise it! 

>Navigation (prev. && next episode) maybe?
>Do we really need this? There is a breadcrumb for full Show view with all the episodes. 
And of course when we have the tags and all, to have the Related Episodes also...

Yeah, I guess you are right both about the related episodes and the breadcrumbs. Breadcrumbs are important to me but in this flow it's an extra click and re-orientate to go from ep 1 to 2. That's why I wrote the idea of episode-level navigation. We can put it to the backlog if it is too much of a scope creep!

>Maybe better would be the Show arcsi episodes list with images and titles, as on the show page, just smaller?

You are right and it got me thinking about a new layout where shows detail page display archive episodes as list w/ less info but easier discoverability/browsability. So you go to archive to see and browse the episodes, I think it is great for that. But on the shows page these boxes make it bit slow to scroll through at least that's how I perceive it.

I think we just might be still in time to let Csenge know. What do you think, is it worth it to discuss this, if it is, would you talk with her about this option? 

Thanks for all the good comments!

**Comment by baxgas** [comment]
We'll leave this issue open for further refinement

**Comment by pvj** [comment]
Okay, sounds coool but can you tell me what I should do here as you assigned it? I'm happy to help just don't know what I need to do, sorry!

**Comment by baxgas** [comment]
Oh, sorry, no need to actively code here, just to note there are some dependencies still left. If you want just take out yourself

**Comment by pvj** [comment]
Makes sense I get it now thanks
