### ISSUE TITLE
Display show status (active|past) on show details page 

### ISSUE THREAD

**Issue by pvj** [mmmnmnm/lahmacun_rework#147]
This is the only current meta-data that I think we don't display but we should

**Comment by pvj** [comment]
Another thing missing from show details page: 

Outgoing links: Mixcloud, Soundcloud, bandcamp, instagram, etc. This is also totally missing from arcsi as separate column, it's just part of the main desc. This might be separated out and implemented after release, if you think so. No pressure just wanted to capture before it eludes me again.

**Comment by baxgas** [comment]
Sure, after MVP and arcsi fixes
