### ISSUE TITLE
New news item will not refresh on home 

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun_rework#194]

**Comment by baxgas** [comment]
It is store related (it caches the response and doesn't fetch every time) ÷ should I rework for fetch on every page load?

**Comment by gammaw** [comment]
> It is store related (it caches the response and doesn't fetch every time) ÷ should I rework for fetch on every page load?

I think yes. For me it would be the expected behavior when I navigate back and forth between pages.

**Comment by baxgas** [comment]
> > It is store related (it caches the response and doesn't fetch every time) ÷ should I rework for fetch on every page load?
> 
> I think yes. For me it would be the expected behavior when I navigate back and forth between pages.

@gammaw see https://github.com/mmmnmnm/lahmacun_rework/pull/203/commits/896d80589eae33a141110219e78e8cdd897e6fe4
