### ISSUE TITLE
Wrong schedule render on big display (2560 x 1440)

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun_rework#195]
![267190670_699084167663141_6067534441729574500_n](https://user-images.githubusercontent.com/28865986/146022677-2450be42-8361-487b-99f0-5d2b33b0000a.jpg)

**Comment by baxgas** [comment]
+ the stream player is really ugly when there are long titles: suggestion,
rework the triangular volume slider to simple horizonal slider

**Comment by baxgas** [comment]
might need some additional checking, but have no access to real large screen. full width players might be a bit problematic also
