### ISSUE TITLE
Rich text for show description etc.

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun_rework#198]
Root cause: arcsi stores plain text. 
Note for this issue: Probably there will be an arcsi side of this issue too but let's collect the Luca feedback here and then we distribute.

**Comment by baxgas** [comment]
@pvj I think a `markdown editor` would be the [best](https://www.npmjs.com/package/@nuxtjs/markdownit), safety and simplicity-wise. hope it is available as a plugin for **jinja** – _what do you think?_

**Comment by pvj** [comment]
The legacy now is HTML, so we just need to have HTML coming from the arcsi api show descriptions. I will check this. 

The long term editor for show hosts should be simple like markdown, I agree yes!
