### ISSUE TITLE
Display custom schedule info 

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun_rework#206]
E.g., New Year's Eve live show, events etc. 

In WP it's easy, cause we simply edit a static HTML file, with our new site where we get the schedule info from arcsi, it's trickier. Any idea?

**Comment by baxgas** [comment]
@gammaw yes, it is a bit trickier, but there could be some solutions, let's discuss which is the best...

**Comment by gammaw** [comment]
Sure, why not try it here :) Maybe the easiest for now would be to add the one-time show in arcsi and set the regular shows temporarily inactive. What do you think?

**Comment by baxgas** [comment]
One-day wordpress custom post with custom fields
