### ISSUE TITLE
Collect & fix Sentry errors

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun_rework#209]
@baxgas how about listing the Sentry errors we see (app errors found via Sentry logs) and add the fixes wherever it's meaningful/necessary? We could use a checklist in this issue and/or spawn new issues if the an error is of bigger scope. What do you think?

**Comment by baxgas** [comment]
@gammaw definitely, but I would need access to the Sentry admin, some of the mistakes are definitely rubbish, eg. `stream is interrupted`, probably on CRON restart or some links pointing to non existing pages (`teszt-gallery`)

**Comment by baxgas** [comment]
A basic TODO to reduce the number of Sentry errors
- [ ] Remove the stream interrupted errors (just console.log?)
- [ ] Rebuild the slug cache to avoid pointing to non existent pages?

**Comment by gammaw** [comment]
Thanks @baxgas!

> Remove the stream interrupted errors (just console.log?)

Wouldn't be even better a local error log file?

**Comment by baxgas** [comment]
@gammaw I don't really see a big point in local error log file, since the vue/nuxt is basically a client-side app (SSR for SEO and caching), but if we need, maybe we could go with this
https://www.npmjs.com/package/nuxt-log

**Comment by gammaw** [comment]
> I don't really see a big point in local error log file, since the vue/nuxt is basically a client-side app (SSR for SEO and caching),

That's a good point!
