### ISSUE TITLE
Schedule popup box - add description under the image

### ISSUE THREAD

**Issue by baxgas** [mmmnmnm/lahmacun_rework#71]

**Comment by baxgas** [comment]
We need a design for this, the description is too long, doesn't make sense to have a small box, but the large would cover a lot of espace.

**Comment by pvj** [comment]
How about we add some other info (using only icons?) like talk vs. music | new show vs. repeat | something else? Could be small version of the infobox concept of the shows pages.

**Comment by baxgas** [comment]
@pvj great idea, but I think we should revise the popup cover design concept, I think it would be worth to have a bigger box/popup somehow with the infos of the playing episode (last item in arcsi list), besides cover-image to show the title/description, tags, upload time etc. I would rather think of some kind of info box opening on click, maybe on some icon?

**Comment by pvj** [comment]
@baxgas like an ℹ️ icon?
