### ISSUE TITLE
Restructure component names to folder structures - usages

### ISSUE THREAD

**Issue by baxgas** [mmmnmnm/lahmacun_rework#73]

**Comment by pvj** [comment]
My idea was to rename ScheduleHome to ScheduleDailyList where the naming schema is <component_type><range><display_type> 

so we have ScheduleWeeklyList ScheduleDailyGrid ScheduleWeeklyGrid etc. 

But please everyone chime in

**Comment by baxgas** [comment]
@pvj good point, we can have different folders per section, it can be done from now on
and also it will be easy to refactor when we have some stable structure
