### ISSUE TITLE
Rework stream player according to design

### ISSUE THREAD

**Issue by baxgas** [mmmnmnm/lahmacun_rework#74]

**Comment by pvj** [comment]
Here I would also maybe discuss or figure out if we should have some settable configuration list / options for the player(s)

Examples from our prev. discussions: 

- show album art
- display elapsed time
- display remaining time
- display chatbox
- display ON AIR banner
- etc.

Later maybe we could also display these on the front-end. I haven't really seen web radios where you can as user define your player but I think it would be cool and huge opportunity to make the radio/player more user-friendly

**Comment by baxgas** [comment]
@pvj customisable player is a good idea indeed! But for now, especially since arcsi is a different player, I think it is better to focus on functional features and afterwards turn to special ones

**Comment by pvj** [comment]
@baxgas I think we could make 1 player then use different config values and voila -- we have radio player and an arcsi player for different use-cases. So yes the goal is to have something different for both but I think we could get that w/ the effort of developing only 1. It would be feature rich but wouldn't have anything special just the main functionality that is needed by both

F.e.: same player codebase but arcsi.conf has `{ displayTime: true, skipBwd: true, skipFwd: true, showCover: true }` where radio.conf has `{ displayTime: false, skipBwd: true, skipFwd: false, showCover: false }` etc. 

Or do you think we should start with 2 separated players then bring them together?

**Comment by baxgas** [comment]
is done in #88
