### ISSUE TITLE
Implement player for Arcsi episodes

### ISSUE THREAD

**Issue by baxgas** [mmmnmnm/lahmacun_rework#75]
For now a basic one, wait/discuss for the design
Structure: play/pause, forward, backward, volume, download
Would be good to have it stay on, while navigating to other pages

Custom component (mini-player) from:
https://github.com/mickdekkers/vue-howler

**Comment by pvj** [comment]
Also one request from user: 

If we could somehow mark/remember where they left off. Not sure how big this feature is probably very big. I'm happy to do some digging / research how this could be achieved anonymously via cookies or local storage

**Comment by baxgas** [comment]
@pvj look: 
https://github.com/mickdekkers/vue-howler#setseekseek
can be set in a Local Storage / Cookie and then read back

**Comment by pvj** [comment]
Wow good find! 

Do we already use this mixin? I'm sad to see it says in the description that it is `[UNMAINTAINED]` Maybe there is another one to use, or we may contact the author and maintain it if it is something we need anyway? (That's lots of extra work however, I'll take this to our tech meet for further discussion)
