### ISSUE TITLE
Same container for news and schedule on frontpage

### ISSUE THREAD

**Issue by pvj** [mmmnmnm/lahmacun_rework#78]
Related to #77 we decided on Saturday that these two would always be equal sitting next to each other.

**Comment by baxgas** [comment]
@pvj why is this a separate issue? isn't it the same az #77 ?

**Comment by pvj** [comment]
Well, yes and no because this is more about news and schedule having the same container (frontPageContainer?) -- the other is about the properties of the container (fix vs. dynamic height, etc.)

So they are related and feel free to merge them or close them if you think this is dupe!
