### ISSUE TITLE
Photos / gallery 

### ISSUE THREAD

**Issue by pvj** [mmmnmnm/lahmacun_rework#79]
We would like to have dedicated photo / gallery capability

- layout
- page
- appearance on the navbar

**Comment by baxgas** [comment]
It needs some rework from the current solution on the wp page, since the plugin doesn't expose a REST API endpoint.
But, first we should have some form of visual design from Csenge/Marci?

**Comment by baxgas** [comment]
See https://github.com/mmmnmnm/lahmacun/issues/440 after REST is working, connect to nuxt and loop over
