### ISSUE TITLE
Optimize and refactor Arcsi player History

### ISSUE THREAD

**Issue by baxgas** [mmmnmnm/lahmacun_rework#86]
Save Id only once, and then change the playposition and play time infos under that entry.
**Structure**
ArcsiHistory = {
  'episodeID' : [
     playDate: 'time',
     playPosition: 'position'
  ],
  'episodeID' : [
     playDate: 'time',
     playPosition: 'position'
  ],
  ...
}

**Mutation**
newData = {  
  'currentEpisodeID' : [
     playDate: 'currentTime',
     playPosition: 'currentPosition'
  ]
}
Object.assign(ArcsiHistory, newData)

**Comment by pvj** [comment]
Is each object session/user specific? I will try to ask with an example: if I listen to 16:40 and stop but you listen to 23:58 then when I load again is it 16:40 or 23:58?

**Comment by baxgas** [comment]
Handling is Session specific.
User specific would need login
