### ISSUE TITLE
Unify Arcsi and Stream audio player in one component

### ISSUE THREAD

**Issue by baxgas** [mmmnmnm/lahmacun_rework#87]
One component with Hammer.js library, if%else prop for arcsi or stream.
Design stays, audio handled by hammer.js

**Comment by baxgas** [comment]
@gammaw @pvj 
I researched this issue a bit, and I would leave this for now, it doesn't make big sense, since the stream player works fine. It would make some sense if we use one player for both.
I'll close this issue now.

**Comment by baxgas** [comment]
In howler/native audio api question, I think the wide compatibility will be decisive, it seems howler doesn't perform well with the mobile controls, see https://github.com/mmmnmnm/lahmacun_rework/issues/103
We'll see if it can be solved. if not, the best would be to rework the arcsi player to audio API 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio
https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API

**Comment by gammaw** [comment]
@baxgas while reviewing this https://github.com/mmmnmnm/lahmacun_rework/pull/132 I noticed that we have `RadioPlayer.vue` and `arcsi/Player.vue` (the latter one is used to instantiate `BottomArcsiPlayer.vue`). When we said to have one reusable component for both players (radio and stream), didn't we mean to have just one player component that we use to instantiate the specific players? Do you think it would be possible and sensible?

**Comment by baxgas** [comment]
Yes, I know we discussed it, but since the logic is so different, I think
it is not necessary, and would be much mess to push the component in
that direction.
What would be the benefits?

**Comment by gammaw** [comment]
If there are no reusable features that none. So that's an answer for now. Should we close this one?

**Comment by baxgas** [comment]
That would make sense if we would have used howler instead of html audio
and componentise that as a simple audio interface.
Can be closed for now
