### ISSUE TITLE
Home design update

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun_rework#88]

**Comment by baxgas** [comment]
@pvj - in accordance to streamline the Arcsi API calls, I think it is the best to do it here with the **Arcsi's latest** block, to have a new json endpoint query, eg. arcsiServerURL/latest which should give back just the latest 9 shows in a list
![image](https://user-images.githubusercontent.com/36408851/127765407-87bb9c08-1d1c-490c-85f8-a6a7844d4e12.png)

**Comment by baxgas** [comment]
@pvj - as discussed, also it would be handy to think about the usage of `arcsiServerURL/shows/all` endpoint, to have another optimized endpoint, just listing the necessary `shows` Infos, without all the `episodes` in it that makes the results object quite huge.
So, in the start-query there would be just the basic `shows` infos: name, id, schedule-date...
And then the `episode` (/item/id) data would be fetched just on-demand, as I already implemented it in the arcsi-episode endpage 
As I saw by the progress of the Swagger implementation these should be not a big problem to implement

**Comment by gammaw** [comment]
Can't we now work with the API we have, abstract away the query itself so that we can replace it later on when we have new endpoints without having to change the frontend logic? The query would be a bit complicated at the moment and the call may take a bit more time to complete but it's not that bad I think.

**Comment by baxgas** [comment]
Can be done, but it is a bit overkill to search through the big json file to collect the latest episodes two-three level deep in the hierarchy
